spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: DBA123
    url: jdbc:mysql://localhost:3306/
    username: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp   
      
server:
  port: 9890
  servlet:
    context-path: /phonebook_webapp     
